### ISSUE TITLE
transformed kernel initialization

### ISSUE THREAD

**Issue by andravin** [xingyul/Sparse-Winograd-CNN#3]
As far as I can tell, the initialization technique used for the transformed kernel is not documented in the research paper, "Efficient Sparse-Winograd Convolutional Neural Networks". 

Is this the initialization that was used to generate the results in the paper:

https://github.com/xingyul/Sparse-Winograd-CNN/blob/91ea6f08a96701a2226a14a868b7301094f2c72a/ResNet-18-var/winograd_conv.py#L19

Can you document how you derived this formula?

**Comment by xingyul** [comment]
Thanks for your interest in this initialization technique.

The goal of good initialization is essentially setting a proper initial variance for the weights so that the activation variance stays the same across layers. 

The factor 2 is from “Delving Deep into Rectifiers” in [here](https://www.tensorflow.org/api_docs/python/tf/contrib/layers/variance_scaling_initializer). 

In Vanilla CNN with kernel size 3, there’re 9(=3x3) weight-activation element-wise product (wi*aj) summing up to 1 output element.  

Winograd-ReLU however, first transforms input activation by summing/subtracting 4 activations to form 1 transformed input activation. Then it performs element-wise multiply with weight, before transforming output activation by summing/subtracting 8 product values to form 1 output activation. So it’s essentially turning 32 weight-activation element-wise product into 1 output element.

To offset this difference compared to vanilla CNN, in Winograd-ReLU weight initialization, we multiply the initial weight variance by 9.0/32.0. Reflected in the implementation of tf.contrib.layers.variance_scaling_initializer(), we just scale the original factor argument of 2.0 by 9.0/32.0 and still keep ‘FAN_IN’ mode.

**Comment by andravin** [comment]
I think there might be some issues with the derivation of the weights  initialization.

The output transform actually has 9 terms per output, not 8.

Also, according to the source code, `tf.contrib.layers.variance_scaling_initializer` will automatically include a factor of 16, because that is the first dimension of the weights tensor. The weights tensor is 16xCxK, so fan_in = 16*C

In the case of a regular 3x3 convolutional layer, it would automatically include a factor of 9, because the weights tensor would be 3x3xCxK, so fan_in = 9*C.

Also, the addition of variances only holds if the variables are independent. But the activations in a single channel tend to be highly correlated.

Therefore the input transform will actually reduce the variance in 15 of the 16 winograd components. In the remaining component, the one that is the sum over a 2x2 tile, we should expect the variance to be increased by more than a factor of 4, because the variances and covariances add .. it would increase by up to a factor of 16 if the variables are perfectly correlated.

Thank you for your response, and I hope this is interesting to anybody who is trying to reproduce the experiments in the paper.
